[theme]
primaryColor = "#530fe6"
backgroundColor = "#F5F6FA"
secondaryBackgroundColor = "#E9ECF2"
textColor = "#1F2937"


[client]
toolbarMode = "viewer"

[ui]
hideTopBar = true


[server]
headless = true